"""feat(models.db.User): add ts cols

Revision ID: 1e34ea21b862
Revises: 4721f4494b11
Create Date: 2025-10-10 10:03:03.193148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e34ea21b862'
down_revision: Union[str, Sequence[str], None] = '4721f4494b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_fetch_ts', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('created_ts', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_ts')
    op.drop_column('user', 'last_fetch_ts')
    # ### end Alembic commands ###
