"""feat(item): add last_fetch_ts and edited_ts columns

Revision ID: 4b98ad74cabc
Revises: f57bbac524e5
Create Date: 2025-10-08 14:15:54.681502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b98ad74cabc'
down_revision: Union[str, Sequence[str], None] = 'f57bbac524e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    import datetime

    op.add_column('items', sa.Column('last_fetch_ts', sa.DateTime(), nullable=True))
    op.add_column('items', sa.Column('edited_ts', sa.DateTime(), nullable=True))

    items = sa.sql.table(
        'items', sa.sql.column('last_fetch_ts', sa.DateTime())
    )

    op.execute(
        items.update().values(
            last_fetch_ts=datetime.datetime(1970,1,1,0,0,0)
        )
    )

    items = sa.sql.table(
        'items', sa.sql.column('edited_ts', sa.DateTime())
    )

    op.execute(
        items.update().values(
            edited_ts=datetime.datetime(1970,1,1,0,0,0)
        )
    )

    op.alter_column('items', 'last_fetch_ts', nullable=False)
    op.alter_column('items', 'edited_ts', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'edited_ts')
    op.drop_column('items', 'last_fetch_ts')
    # ### end Alembic commands ###
