"""feat(items): add retry_count column

Revision ID: 4721f4494b11
Revises: 4b98ad74cabc
Create Date: 2025-10-10 07:54:56.775448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4721f4494b11'
down_revision: Union[str, Sequence[str], None] = '4b98ad74cabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('retry_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'retry_count')
    # ### end Alembic commands ###
